CREATE TABLE IF NOT EXISTS `shared_folders` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `parent_id` bigint unsigned DEFAULT NULL,
  `name` varchar(255) NOT NULL,
  `description` text DEFAULT NULL,
  `visibility` enum('private','internal','client','public') NOT NULL DEFAULT 'internal',
  `owner_id` bigint unsigned DEFAULT NULL,
  `context_type` varchar(255) DEFAULT NULL,
  `context_id` bigint unsigned DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  `deleted_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `shared_folders_parent_id_name_index` (`parent_id`,`name`),
  KEY `shared_folders_visibility_owner_id_index` (`visibility`,`owner_id`),
  KEY `shared_folders_context_type_context_id_index` (`context_type`,`context_id`),
  CONSTRAINT `shared_folders_owner_id_foreign` FOREIGN KEY (`owner_id`) REFERENCES `users` (`id`) ON DELETE SET NULL,
  CONSTRAINT `shared_folders_parent_id_foreign` FOREIGN KEY (`parent_id`) REFERENCES `shared_folders` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `shared_files` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `uuid` char(36) NOT NULL,
  `folder_id` bigint unsigned DEFAULT NULL,
  `display_name` varchar(255) NOT NULL,
  `original_name` varchar(255) DEFAULT NULL,
  `disk` varchar(50) NOT NULL DEFAULT 'local',
  `path` varchar(255) NOT NULL,
  `extension` varchar(20) DEFAULT NULL,
  `mime_type` varchar(255) DEFAULT NULL,
  `size_bytes` bigint unsigned NOT NULL DEFAULT '0',
  `checksum` varchar(64) DEFAULT NULL,
  `version_no` int unsigned NOT NULL DEFAULT '1',
  `visibility` enum('private','internal','client','public') NOT NULL DEFAULT 'internal',
  `is_locked` tinyint(1) NOT NULL DEFAULT '0',
  `uploaded_by` bigint unsigned DEFAULT NULL,
  `expires_at` timestamp NULL DEFAULT NULL,
  `context_type` varchar(255) DEFAULT NULL,
  `context_id` bigint unsigned DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  `deleted_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `shared_files_uuid_unique` (`uuid`),
  KEY `shared_files_folder_id_display_name_index` (`folder_id`,`display_name`),
  KEY `shared_files_visibility_uploaded_by_index` (`visibility`,`uploaded_by`),
  KEY `shared_files_context_type_context_id_index` (`context_type`,`context_id`),
  CONSTRAINT `shared_files_folder_id_foreign` FOREIGN KEY (`folder_id`) REFERENCES `shared_folders` (`id`) ON DELETE SET NULL,
  CONSTRAINT `shared_files_uploaded_by_foreign` FOREIGN KEY (`uploaded_by`) REFERENCES `users` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `shared_file_versions` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `shared_file_id` bigint unsigned NOT NULL,
  `version_no` int unsigned NOT NULL,
  `disk` varchar(50) NOT NULL,
  `path` varchar(255) NOT NULL,
  `original_name` varchar(255) DEFAULT NULL,
  `extension` varchar(20) DEFAULT NULL,
  `mime_type` varchar(255) DEFAULT NULL,
  `size_bytes` bigint unsigned NOT NULL DEFAULT '0',
  `checksum` varchar(64) DEFAULT NULL,
  `change_note` text DEFAULT NULL,
  `uploaded_by` bigint unsigned DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `shared_file_versions_shared_file_id_version_no_unique` (`shared_file_id`,`version_no`),
  CONSTRAINT `shared_file_versions_shared_file_id_foreign` FOREIGN KEY (`shared_file_id`) REFERENCES `shared_files` (`id`) ON DELETE CASCADE,
  CONSTRAINT `shared_file_versions_uploaded_by_foreign` FOREIGN KEY (`uploaded_by`) REFERENCES `users` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `file_shares` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `shared_file_id` bigint unsigned DEFAULT NULL,
  `shared_folder_id` bigint unsigned DEFAULT NULL,
  `share_type` enum('staff','client','public') NOT NULL DEFAULT 'staff',
  `access_level` enum('view','download','upload','manage') NOT NULL DEFAULT 'view',
  `shared_with_user_id` bigint unsigned DEFAULT NULL,
  `shared_with_email` varchar(255) DEFAULT NULL,
  `share_token` varchar(100) DEFAULT NULL,
  `password` varchar(255) DEFAULT NULL,
  `max_downloads` int unsigned DEFAULT NULL,
  `download_count` int unsigned NOT NULL DEFAULT '0',
  `expires_at` timestamp NULL DEFAULT NULL,
  `is_active` tinyint(1) NOT NULL DEFAULT '1',
  `created_by` bigint unsigned DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `file_shares_share_token_unique` (`share_token`),
  KEY `file_shares_share_type_is_active_index` (`share_type`,`is_active`),
  KEY `file_shares_shared_with_user_id_shared_with_email_index` (`shared_with_user_id`,`shared_with_email`),
  CONSTRAINT `file_shares_created_by_foreign` FOREIGN KEY (`created_by`) REFERENCES `users` (`id`) ON DELETE SET NULL,
  CONSTRAINT `file_shares_shared_file_id_foreign` FOREIGN KEY (`shared_file_id`) REFERENCES `shared_files` (`id`) ON DELETE CASCADE,
  CONSTRAINT `file_shares_shared_folder_id_foreign` FOREIGN KEY (`shared_folder_id`) REFERENCES `shared_folders` (`id`) ON DELETE CASCADE,
  CONSTRAINT `file_shares_shared_with_user_id_foreign` FOREIGN KEY (`shared_with_user_id`) REFERENCES `users` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `file_access_logs` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `shared_file_id` bigint unsigned DEFAULT NULL,
  `file_share_id` bigint unsigned DEFAULT NULL,
  `user_id` bigint unsigned DEFAULT NULL,
  `action` enum('uploaded','previewed','downloaded','shared','revoked','deleted') NOT NULL DEFAULT 'previewed',
  `ip_address` varchar(45) DEFAULT NULL,
  `user_agent` text DEFAULT NULL,
  `notes` text DEFAULT NULL,
  `context_type` varchar(255) DEFAULT NULL,
  `context_id` bigint unsigned DEFAULT NULL,
  `accessed_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `file_access_logs_action_accessed_at_index` (`action`,`accessed_at`),
  KEY `file_access_logs_context_type_context_id_index` (`context_type`,`context_id`),
  KEY `file_access_logs_shared_file_id_foreign` (`shared_file_id`),
  KEY `file_access_logs_file_share_id_foreign` (`file_share_id`),
  KEY `file_access_logs_user_id_foreign` (`user_id`),
  CONSTRAINT `file_access_logs_file_share_id_foreign` FOREIGN KEY (`file_share_id`) REFERENCES `file_shares` (`id`) ON DELETE SET NULL,
  CONSTRAINT `file_access_logs_shared_file_id_foreign` FOREIGN KEY (`shared_file_id`) REFERENCES `shared_files` (`id`) ON DELETE SET NULL,
  CONSTRAINT `file_access_logs_user_id_foreign` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
