services:
  mysql:
    image: "mysql:8.0"
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "root_password"
      MYSQL_DATABASE: "elisoft_erp"
      MYSQL_USER: "elisoft_user"
      MYSQL_PASSWORD: "user_password"
    volumes:
      - "mysql_data:/var/lib/mysql"
    networks:
      - elisoft_net

  maildev:
    image: maildev/maildev
    container_name: elisoft_maildev
    restart: unless-stopped
    ports:
      - "1080:1080"
      - "1025:1025"
    networks:
      - elisoft_net
  phpmyadmin:
    image: phpmyadmin:latest
    ports:
      - "8080:80"
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
    networks:
      - elisoft_net
    depends_on:
      - mysql

  redis:
    image: "redis:7.2"
    container_name: elisoft_redis
    ports:
      - "16379:6379"
    restart: unless-stopped
    networks:
      - elisoft_net

  pgvector:
    image: pgvector/pgvector:pg17
    container_name: elisoft_pgvector
    restart: unless-stopped
    ports:
      - "15432:5432"
    environment:
      POSTGRES_DB: elisoft_vectors
      POSTGRES_USER: vector_user
      POSTGRES_PASSWORD: vector_password
    volumes:
      - pgvector_data:/var/lib/postgresql/data
    networks:
      - elisoft_net

networks:
  elisoft_net:
    driver: bridge

volumes:
  mysql_data:
    driver: local
  pgvector_data:
    driver: local
