<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>{{ $statement->title }}</title>
    <style>
        body { font-family: sans-serif; font-size: 12px; color: #333; }
        h1, h2 { text-align: center; color: #111; margin: 5px 0; }
        p { text-align: center; color: #555; }
        .details { margin-bottom: 20px; font-size: 11px; text-align: right;}
        table { width: 100%; border-collapse: collapse; margin-top: 15px; }
        th, td { border: 1px solid #ddd; padding: 8px; text-align: left; }
        th { background-color: #f8f9fa; font-weight: bold; }
        .text-right { text-align: right; }
        .amount { font-family: monospace; }
        .footer { position: fixed; bottom: 0; width: 100%; text-align: center; font-size: 10px; color: #777; border-top: 1px solid #ddd; padding-top: 5px; }
    </style>
</head>
<body>
    <h1>{{ $companyName ?? 'Cawee' }}</h1>
    <h2>{{ $statement->title }}</h2>
    <p>Reference: {{ $statement->reference }} | As Of: {{ $statement->as_of_date?->format('d M Y') }}</p>

    <div class="details">
        Generated At: {{ $generatedAt }} <br>
        Generated By: {{ $generatedBy }}
    </div>

    @if($statement->statement_type === 'trial_balance' && isset($records) && $records->count() > 0)
        <table>
            <thead>
                <tr>
                    <th>Account Code</th>
                    <th>Account Name</th>
                    <th class="text-right">Opening Balance</th>
                    <th class="text-right">Dr Movement</th>
                    <th class="text-right">Cr Movement</th>
                    <th class="text-right">Closing Balance</th>
                </tr>
            </thead>
            <tbody>
                @foreach($records as $rec)
                <tr>
                    <td>{{ $rec['code'] }}</td>
                    <td>{{ $rec['name'] }}</td>
                    <td class="text-right amount">{{ number_format($rec['opening_balance'], 2) }}</td>
                    <td class="text-right amount">{{ number_format($rec['total_debit'], 2) }}</td>
                    <td class="text-right amount">{{ number_format($rec['total_credit'], 2) }}</td>
                    <td class="text-right amount">{{ number_format($rec['closing_balance'], 2) }}</td>
                </tr>
                @endforeach
            </tbody>
        </table>
    @else
        <div style="text-align: center; padding: 40px; border: 1px dashed #ccc; margin-top: 20px;">
            <h3 style="color: #888;">Report Generation Placeholder</h3>
            <p style="color: #999;">The mapping logic for {{ str_replace('_', ' ', $statement->statement_type) }} is being finalized.</p>
        </div>
    @endif

    <div class="footer">
        Confidential Financial Report - Cawee ERP System
    </div>
</body>
</html>
